spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:21527/railway
    username: postgres
    password: VHtzKZBdtAsyVKCbDyjusIFpBejIqHzL
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect